info:
  app:
    name: '@pom.artifactId@'
    description: '@pom.description@'
    version: '@pom.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'

server:
  port: 5000
  compression:
    enabled: true
  forward-headers-strategy: framework
  shutdown: graceful
  servlet:
    contextPath: /client
    session:
      cookie:
        http-only: true
        secure: false
    encoding:
      enabled: true
      charset: UTF-8
  undertow:
    url-charset: UTF-8

springdoc:
  swagger-ui:
    docExpansion: none
    enabled: true
  api-docs:
    enabled: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:clientpoc
    username: sa
    password: password
    hikari:
      driver-class-name: org.h2.Driver
    dbcp2:
      driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
